version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    environment:
      # No auth for local development; omit API key entirely.
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      # Keep single-node simple for local dev
      QDRANT__CLUSTER__ENABLED: "false"
      # Enable CORS for local tools if needed
      QDRANT__SERVICE__ENABLE_CORS: "true"
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5


