class QQErrorCodes:
    ERR_QUERY_ARGS_MISSING = "ERR_QUERY_ARGS_MISSING"
    ERR_DUPLICATE_DOC = "ERR_DUPLICATE_DOC"
    ERR_NEARDUP_DOC = "ERR_NEARDUP_DOC"
    ERR_OPENAI_KEY_MISSING = "ERR_OPENAI_KEY_MISSING"
    ERR_GOOGLE_KEY_MISSING = "ERR_GOOGLE_KEY_MISSING"
    ERR_MODEL_UNAVAILABLE = "ERR_MODEL_UNAVAILABLE"
    ERR_SESSION_EXPIRED = "ERR_SESSION_EXPIRED"
    ERR_TOKEN_CAP_EXCEEDED = "ERR_TOKEN_CAP_EXCEEDED"
    ERR_WRITE_NOT_ALLOWED = "ERR_WRITE_NOT_ALLOWED"
    ERR_POLICY_GUARD = "ERR_POLICY_GUARD"
    ERR_VECTOR_UNAVAILABLE = "ERR_VECTOR_UNAVAILABLE"

