services:
  qq-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qq-api
    restart: unless-stopped
    environment:
      QQ_EMBED_MODEL: sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - /run:/run
    tmpfs:
      - /dev/shm:size=1g
      - /dev/shm/hf:size=2g
